scaling:
  varaible_name_to_scalers:

    nodal_nadj:
      method: identity

    nodal_x_grad_hop1:
      method: isoam_scale
      parameters:
        other_components:
          - nodal_y_grad_hop1
          - nodal_z_grad_hop1
    nodal_y_grad_hop1:
      same_as: nodal_x_grad_hop1
      join_fitting: true
    nodal_z_grad_hop1:
      same_as: nodal_x_grad_hop1
      join_fitting: true

    nodal_initial_u:
      method: std_scale
    nodal_last_u:
      same_as: nodal_initial_u
      join_fitting: false

training:
  batch_size: 1
  random_seed: 0
  optimizer_setting:
    optimizer: SGD
    parameters:
      lr: 0.0001
  loss_setting:
    name2loss:
      nodal_last_u: "mse"

model:
  inputs:
    - name: nodal_initial_u
      physical_dimension: {"L": 1, "T": -1}
    
  labels:
    - name: nodal_last_u
      physical_dimension: {"L": 1, "T": -1}
  
  fields:
    - name: "nodal_nadj"
      physical_dimension: {}

  network:
    nn_type: GROUP
    name: DEMO
    inputs:
      - name: nodal_initial_u
        n_last_dim: 1
    
    outputs:
      - name: nodal_last_u
        n_last_dim: 1

    modules:
      - nn_type: MLP
        name: MLP0
        input_keys:
          - nodal_initial_u
        output_key: nodal_last_u
        nn_parameters:
          nodes: [-1, 16, 1]
          activations: ["identity", "identity"]
          bias: False

