stateDiagram
    direction LR
    classDef alignCenter text-align:center
    state "MLP0
nn_type: MLP
n_nodes: [100, 20, 200]" as state_0
    state "MLP1
nn_type: MLP
n_nodes: [200, 20, 200]" as state_1
    state "CONCAT
nn_type: Concatenator
n_nodes: [400, 400]" as state_2
    state_0 --> state_2: Pipe
    state_1 --> state_2: Pipe
    state_2 --> [*]
    class state_0, state_1, state_2 alignCenter